DjangoFirstSocial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("posts/", include("posts.urls", namespace="posts")),
]

accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"
urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name="user_register"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
    path("profile/<int:user_id>", views.UserProfileView.as_view(), name="user_profile"),
    path("reset/", views.UserPasswordResetView.as_view(), name="reset_password"),
    path(
        "password_reset_done/",
        views.UserPasswordResetDone.as_view(),
        name="password_reset_done",
    ),
    path(
        "confirm/<uidb64>/<token>/",
        views.UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/complete/",
        views.UserPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("follow/<int:user_id>/SS", views.UserFollowView.as_view(), name="user_follow"),
    path(
        "unfollow/<int:user_id>/",
        views.UserUnfollowView.as_view(),
        name="user_unfollow",
    ),
    path("edit_user/", views.EditUserView.as_view(), name="edit_user"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

posts/urls.py
from django.urls import path

from .views import *

app_name = "posts"
urlpatterns = [
    path(
        "<int:post_id>/<str:post_slug>/", PostDetailView.as_view(), name="post_detail"
    ),
    path("delete/<int:post_id>/", PostDeleteView.as_view(), name="post_delete"),
    path("update/<int:post_id>/", PostUpdateView.as_view(), name="post_update"),
    path("create/", PostCreateView.as_view(), name="post_create"),
    path(
        "reply/<int:post_id>/<int:comment_id>",
        PostAddReplyView.as_view(),
        name="add_reply",
    ),
    path("like/<int:post_id>/", PostLikeView.as_view(), name="post_like"),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Relation(models.Model):
    from_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="follower"
    )
    to_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.from_user} followed {self.to_user} at {self.created_at}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)

accounts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

from .models import Profile


class UserRegisterForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "john doe"}
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "johnDoe@gmail.com"}
        )
    )
    # the widget is used to hide the password
    # the attrs is used to add a class to the input field
    # this is for html/css classes which used to add a bootstrap class to the input field
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "your password"}
        ),
    )
    password2 = forms.CharField(
        label="confirm password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "confirm password"}
        ),
    )

    def clean_email(self):
        email = self.cleaned_data["email"]
        """
        The blow query is lazy which means that Django wont execute the query until
        the result are "Used" which again means that you used the result in a condition,
        a loop or slicing. only then django executes the query.
        """
        if email and User.objects.filter(email=email).exists():
            raise ValidationError("Email already exists")
        return email

    def clean_username(self):
        username = self.cleaned_data["username"]
        if username and User.objects.filter(username=username).exists():
            raise ValidationError("Username already exists")
        return username

    def clean(self):
        cd = super().clean()
        password1 = cd.get("password1")
        password2 = cd.get("password2")

        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords do not match")


class UserLoginForm(forms.Form):
    username = forms.CharField(
        label="username or email",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "john doe"}
        ),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "your password"}
        )
    )


class ProfileEditForm(forms.ModelForm):
    email = forms.EmailField(
        label="Email",
        required=False,
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "johnDoe@gmail.com"}
        ),
    )

    class Meta:
        model = Profile
        fields = ("bio",)
        widgets = {
            "body": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "rows": 3,
                    "placeholder": "This is your bio",
                }
            )
        }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.contrib import messages
from django.urls import reverse_lazy

from .forms import UserRegisterForm, UserLoginForm, ProfileEditForm
from posts.models import Post
from .models import Relation


class UserRegisterView(View):
    # this is to avoid the reusability of the form in the functions if the form got changed
    form_class = UserRegisterForm
    template_name = "accounts/register.html"

    def dispatch(self, request, *args, **kwargs):
        """
        the dispatch method in class based views is executed before all the
        other methods in the class (get,post,...).
        This is used to check if the user is already logged in or not.
        so it prevent the user to access the login or register page again.
        """
        if request.user.is_authenticated:
            messages.warning(request, "You are already logged in")
            return redirect("home:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(
                username=cd["username"], email=cd["email"], password=cd["password1"]
            )
            messages.success(
                request,
                "Account created successfully",
                extra_tags="alert alert-success",
            )
            return redirect("home:home")
        # if the form is not valid then it will render the form again but with the error messages
        # on the fields it needs (the browser validation is off from the register html)
        # the passed form is the form with the error messages
        return render(request, self.template_name, {"form": form})


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = "accounts/login.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.warning(request, "You are already logged in")
            return redirect("home:home")
        return super().dispatch(request, *args, **kwargs)

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get("next")
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request, username=cd["username"], password=cd["password"]
            )
            if user is not None:
                login(request, user)
                messages.success(
                    request, "Login successful", extra_tags="alert alert-success"
                )
                if self.next:
                    return redirect(self.next)
                return redirect("home:home")
            else:
                messages.error(
                    request,
                    "Invalid username or password",
                    extra_tags="alert alert-danger",
                )
        return render(request, self.template_name, {"form": form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)  # the user is in the request object
        messages.success(request, "Logout successful", extra_tags="alert alert-success")
        return redirect("home:home")


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        is_following = False
        print("request=>", request)
        # the pk look for the primary key in the database wether its id or something else
        user = get_object_or_404(User, pk=user_id)
        # posts = Post.objects.filter(user=user)
        posts = user.posts.all()  # with related_name
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            is_following = True
        return render(
            request,
            "accounts/profile.html",
            {"user": user, "posts": posts, "is_following": is_following},
        )


class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = "accounts/password_reset_form.html"
    # we wait for the evaluation to complete so we use lazy
    success_url = reverse_lazy("accounts:password_reset_done")
    email_template_name = "accounts/password_reset_email.html"


class UserPasswordResetDone(auth_views.PasswordChangeDoneView):
    template_name = "accounts/password_reset_done.html"


class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = "accounts/password_reset_confirm.html"
    success_url = reverse_lazy("accounts:password_reset_complete")


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = "accounts/password_reset_complete.html"


class UserFollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = get_object_or_404(User, pk=user_id)
        relation = Relation.objects.filter(
            from_user=request.user, to_user=user
        ).exists()
        if relation:
            messages.warning(request, "You have already followed this user!")
        else:
            Relation.objects.create(from_user=request.user, to_user=user)
            messages.success(request, "You have followed this user.")
        return redirect("accounts:user_profile", user_id)


class UserUnfollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = get_object_or_404(User, pk=user_id)
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            relation.delete()
            messages.success(request, "You unfollow this user.")
        else:
            messages.warning(request, "You didn't follow this user.")
        return redirect("accounts:user_profile", user_id)


class EditUserView(LoginRequiredMixin, View):
    form_class = ProfileEditForm

    def get(self, request):
        form = self.form_class(
            instance=request.user.profile, initial={"email": request.user.email}
        )
        return render(request, "accounts/edit_profile.html", {"form": form})

    def post(self, request):
        form = self.form_class(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            request.user.email = form.cleaned_data["email"]
            request.user.save()
            messages.success(
                request,
                "your profile has been edited successfully",
                extra_tags="success",
            )
        return redirect("accounts:user_profile", request.user.id)

accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}

{% block content %}

    <form method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit" value="edit">edit</button>
    </form>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
    <h2>Register user</h2>
    {% comment %} # col-md-6 is a bootsrap class to reduce the width of the form fields {% endcomment %}
    <form method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit" value="Login">Register</button>
    </form>

{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

<p class="alert alert-success">Password reset done successfully.</p>

{% endblock content %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
    <h2>Confirm post password</h2>
    {% if validlink %}
    <form method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">submit</button>
    </form>
    {% else %}
        <p class="alert alert-danger">The link is invalid, please try again later.</p>
    {% endif %}
{% endblock content %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<p class="alert alert-success">We sent you an email.</p>

{% endblock content %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:

{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}

{% block content %}
    <h2>Reset Password</h2>
    <form method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">submit</button>
    </form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}

    <h2 class="text-center"> {{user.username}} </h2>

    {% if request.user.id != user.id and not is_following %}
    <a href="{% url "accounts:user_follow" user.id %}" class="btn btn-primary">follow</a>
    {% elif request.user.id != user.id and is_following %}
    <a href="{% url "accounts:user_unfollow" user.id %}" class="btn btn-danger">unfollow</a>
    {% endif %}

    <div class='card'>
        <div class='card-header'>
            <h2>Latest Posts</h2>
        </div>
        <div class='card-body'>
            {% for post in posts %}
                <div class='card'>
                    <div class='card-body'>
                        <a href="{{ post.get_absolute_url }}">{{ post.body|truncatewords:8 }}</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {% if request.user.id == user.id %}
    <a href="{% url "posts:post_create" %}" class="btn btn-primary">Create</a>
    <a href="{% url "accounts:edit_user" %}" class="btn btn-primary">Edit Profile</a>
    {% endif %}

{% endblock content %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
    <h2>Register user</h2>
    {% comment %} # col-md-6 is a bootsrap class to reduce the width of the form fields {% endcomment %}
    <form method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit" value="Register">Register</button>
    </form>

{% endblock content %}