DjangoFirstSocial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("posts/", include("posts.urls", namespace="posts")),
]

accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"
urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name="user_register"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
    path("profile/<int:user_id>", views.UserProfileView.as_view(), name="user_profile"),
    path("reset/", views.UserPasswordResetView.as_view(), name="reset_password"),
    path(
        "password_reset_done/",
        views.UserPasswordResetDone.as_view(),
        name="password_reset_done",
    ),
    path(
        "confirm/<uidb64>/<token>/",
        views.UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/complete/",
        views.UserPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("follow/<int:user_id>/SS", views.UserFollowView.as_view(), name="user_follow"),
    path(
        "unfollow/<int:user_id>/",
        views.UserUnfollowView.as_view(),
        name="user_unfollow",
    ),
    path("edit_user/", views.EditUserView.as_view(), name="edit_user"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        {% comment %} the alert alert is a bootsrap class {% endcomment %}
        <P class="alert alert-{{ msg.tags }}">{{ msg }}</P>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark bg-dark">
  <div class="container-fluid">
      <div class="navbar-nav">
        <a class="nav-link active fw-bold" href="{% url "home:home" %}" style="color:rgb(60, 60, 60);">Home</a>
        {% if request.user.is_authenticated %}
        {% comment %} request.user.id is to pass the user id within the request to the view which is used to render the profile page {% endcomment %}
        <a class="nav-link active fw-bold" href="{% url "accounts:user_profile" request.user.id %}" style="color:rgb(60, 60, 60);">Profile</a>
        <a class="nav-link active fw-bold" href="{% url "accounts:user_logout" %}" style="color:rgb(60, 60, 60);">Logout</a>
        {% else %}
        <a class="nav-link active fw-bold" href="{% url "accounts:user_register" %}" style="color:rgb(60, 60, 60);">Register</a>
        <a class="nav-link active fw-bold" href="{% url "accounts:user_login" %}" style="color:rgb(60, 60, 60);">Login</a>
        {% endif %}
      </div>
    </div>
</nav> 