DjangoFirstSocial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("posts/", include("posts.urls", namespace="posts")),
]

accounts/urls.py
from django.urls import path

from . import views


app_name = "accounts"
urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name="user_register"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
    path("profile/<int:user_id>", views.UserProfileView.as_view(), name="user_profile"),
    path("reset/", views.UserPasswordResetView.as_view(), name="reset_password"),
    path(
        "password_reset_done/",
        views.UserPasswordResetDone.as_view(),
        name="password_reset_done",
    ),
    path(
        "confirm/<uidb64>/<token>/",
        views.UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/complete/",
        views.UserPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("follow/<int:user_id>/SS", views.UserFollowView.as_view(), name="user_follow"),
    path(
        "unfollow/<int:user_id>/",
        views.UserUnfollowView.as_view(),
        name="user_unfollow",
    ),
    path("edit_user/", views.EditUserView.as_view(), name="edit_user"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

posts/urls.py
from django.urls import path

from .views import *

app_name = "posts"
urlpatterns = [
    path(
        "<int:post_id>/<str:post_slug>/", PostDetailView.as_view(), name="post_detail"
    ),
    path("delete/<int:post_id>/", PostDeleteView.as_view(), name="post_delete"),
    path("update/<int:post_id>/", PostUpdateView.as_view(), name="post_update"),
    path("create/", PostCreateView.as_view(), name="post_create"),
    path(
        "reply/<int:post_id>/<int:comment_id>",
        PostAddReplyView.as_view(),
        name="add_reply",
    ),
    path("like/<int:post_id>/", PostLikeView.as_view(), name="post_like"),
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    slug = models.SlugField(max_length=200, unique=True)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-updated_at",)

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("posts:post_detail", args=(self.id, self.slug))

    def like_count(self):
        return self.pvotes.count()

    def user_can_like(self, user):
        user_like = user.uvotes.filter(post=self)
        if user_like.exists():
            return True
        else:
            return False


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="uvotes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="pvotes")

    def __str__(self):
        return f"User {self.user.username} Likes Post {self.post.slug}"

posts/forms.py
from django import forms

from . import models
from home.models import Comment


class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ("slug", "body")
        help_texts = {
            "slug": "write the slug as the example: my-post-slug",
            "body": "The content of the post",
        }


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {
            "body": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 3,
                    "placeholder": "Write your comment here",
                }
            )
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)
        widgets = {
            "body": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 2,
                    "placeholder": "Write your Reply here",
                }
            )
        }

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils.text import slugify
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from .models import Post, Vote
from .forms import PostCreateUpdateForm, CommentCreateForm, CommentReplyForm
from home.models import Comment


class PostDetailView(View):
    form_class = CommentCreateForm
    from_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        # the parameters which passed in the url will save in kwargs
        # we set it to post instance so that django wont confuse it with model Post
        self.post_instance = get_object_or_404(
            Post, pk=kwargs["post_id"], slug=kwargs["post_slug"]
        )
        return super().setup(self, request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        # post = get_object_or_404(Post, pk=post_id, slug=post_slug)
        comments = self.post_instance.pcomment.filter(is_reply=False)
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(
            request.user
        ):
            can_like = True
        return render(
            request,
            "posts/detail.html",
            {
                "post": self.post_instance,
                "comments": comments,
                "form": self.form_class,
                "reply_form": self.from_class_reply,
                "can_like": can_like,
            },
        )

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, "your comment submitted successfully.", "success")
            return redirect(
                "posts:post_detail", self.post_instance.id, self.post_instance.slug
            )


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        if post.user.id == request.user.id:
            try:
                post.delete()
                messages.success(
                    request,
                    "Post deleted successfully",
                    extra_tags="alert alert-success",
                )
            except:
                messages.error(
                    request,
                    "Post could not be deleted",
                    extra_tags="alert alert-danger",
                )
        else:
            messages.error(
                request,
                "You are not allowed to delete this post",
                extra_tags="alert alert-danger",
            )
        return redirect("home:home")


class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def setup(self, request, *args, **kwargs):
        """
        Considering that the setup will execute before dispatch
        we connect to the db here and then use it in different methods
        in order to reduce the times we connect to the db.
        """
        self.post_instance = get_object_or_404(
            Post, pk=kwargs["post_id"]
        )  # we store post in self to have access to it from different methods
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(
                request,
                "You are not allowed to update this post",
                extra_tags="alert alert-danger",
            )
            return redirect("home:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, post_id):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, "posts/update.html", {"form": form})

    def post(self, request, post_id):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            updated_post = form.save(commit=False)
            updated_post.slug = slugify(updated_post.slug)
            updated_post.save()
            messages.success(
                request, "Post updated successfully", extra_tags="alert alert-success"
            )
            return redirect("posts:post_detail", post_id=post.id, post_slug=post.slug)
        else:
            messages.error(
                request, "Post could not be updated", extra_tags="alert alert-danger"
            )
            return render(request, "posts/update.html", {"form": form})


class PostCreateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm

    def get(self, request):
        form = self.form_class()
        return render(request, "posts/create.html", {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid:
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.slug = slugify(new_post.slug)
            new_post.save()
            messages.success(
                request, "Post created successfully", extra_tags="alert alert-success"
            )
            return redirect("posts:post_detail", new_post.id, new_post.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post, pk=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        # print(comment)
        form = self.form_class(request.POST)
        if form.is_valid():
            new_reply = form.save(commit=False)
            new_reply.user = request.user
            new_reply.post = post
            new_reply.reply = comment
            new_reply.is_reply = True
            new_reply.save()
            messages.success(
                request,
                "reply submitted successfully",
                extra_tags="alert alert-success",
            )
        return redirect("posts:post_detail", post_id, post.slug)


class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        vote = Vote.objects.filter(post=post, user=request.user)
        if vote.exists():
            messages.error(
                request,
                "You have already liked this post",
                extra_tags="alert alert-danger",
            )
        else:
            Vote(user=request.user, post=post).save()
            messages.success(request, "You liked this post.")
        return redirect("posts:post_detail", post.id, post.slug)

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}

    <form method="POST" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create</button>
    </form>

{% endblock %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class='card'>
        <div class='card-header'>
            <h3 class="card-subtitle mb-2 text-muted">{{ post.slug }}</h3>
            <a href="{% url 'accounts:user_profile' post.user.id %}" class="text-primary" style="text-decoration: none;">
                {{ post.user.username }}
            </a> - <small class="text-muted">{{ post.updated_at|date:"Y M D" }}</small>
        </div>
        <div class='card-body'>
            <p>{{ post.body }}</p>
        </div>
    </div>

    {% if request.user.id == post.user.id %}
    <a href="{% url 'posts:post_delete' post.id %}" class="btn btn-danger btn-primary">Delete</a>
    <a href="{% url 'posts:post_update' post.id %}" class="btn btn-update btn-primary">Update</a>
    <a href="{% url 'posts:post_like' post.id %}" class="{% if can_like %} disabled {% endif %} btn btn-primary">Like {{post.like_count}}</a>
    {% endif %} <br>

    <h3 class="card-subtitle mb-2 text-muted">Comments</h3>

    {% for comment in comments %}
    <div class="card mb-3">
        <div class="card-header">
            <a href="{% url 'accounts:user_profile' comment.user.id %}" class="text-primary" style="text-decoration: none;">
                {{ comment.user.username }}
            </a> - <small class="text-muted">{{ comment.created_at|timesince }}</small>
        </div>
        <div class="card-body">
            <p class="card-text">{{ comment.body }}</p>

            {% for reply in comment.rcomment.all %}
            <div class="card mb-3">
                <div class="card-header">
                    <a href="{% url 'accounts:user_profile' reply.user.id %}" class="text-primary" style="text-decoration: none;">
                        {{ reply.user.username }}
                    </a> - <small class="text-muted">{{ reply.created_at|timesince }}</small>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ reply.body }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    {% if request.user.is_authenticated %}
        <form action="{% url 'posts:add_reply' post.id comment.id %}" method="POST" class="mt-4">
            {% csrf_token %}
            {{ reply_form.as_p }}
            <button type="submit" class="btn btn-primary">Reply</button>
        </form> <br/>
    {% endif %}

    {% empty %}
    <p class="text-muted">No comments yet!</p>
    {% endfor %}

    {% if request.user.is_authenticated %}
        {% if request.user.id != post.user.id %}
            <form method="POST" class="mt-4">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Comment</button>
            </form>
        {% else %}
            <p class="alert alert-danger">Authors can't comment on their own posts.</p>
        {% endif %}
    {% else %}
        <p class="alert alert-danger">You must be logged in to comment.</p>
    {% endif %}

{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}

    <form method="POST" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>

{% endblock %}